'use client';

import { useState } from 'react';
import { FiFileText, FiX, FiEye } from 'react-icons/fi';

export function SampleDocument() {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <>
      {/* Preview Card */}
      <div
        onClick={() => setIsOpen(true)}
        className="bg-white rounded-xl shadow-lg border border-border overflow-hidden cursor-pointer hover:shadow-xl transition-shadow"
      >
        <div className="flex items-center justify-between p-6 bg-gradient-to-r from-cyan-50 to-blue-50">
          <div className="flex items-center gap-4">
            <div className="p-3 bg-white rounded-lg shadow-sm">
              <FiFileText className="w-6 h-6 text-[#0089eb]" />
            </div>
            <div>
              <h3 className="font-semibold text-gray-900 text-lg">Sample: Late Rent Notice</h3>
              <p className="text-sm text-gray-500">Texas-compliant 3-day notice generated by AI</p>
            </div>
          </div>
          <button className="flex items-center gap-2 px-4 py-2 bg-[#0089eb] text-white rounded-lg hover:bg-[#0070c0] transition-colors">
            <FiEye className="w-4 h-4" />
            View Sample
          </button>
        </div>
      </div>

      {/* Modal */}
      {isOpen && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
          {/* Backdrop */}
          <div
            className="absolute inset-0 bg-black/50"
            onClick={() => setIsOpen(false)}
          />

          {/* Modal Content */}
          <div className="relative bg-white rounded-xl shadow-2xl max-w-3xl w-full max-h-[90vh] overflow-hidden">
            {/* Modal Header */}
            <div className="flex items-center justify-between px-6 py-4 bg-gradient-to-r from-cyan-500 via-blue-500 to-indigo-500 rounded-t-xl">
              <div className="flex items-center gap-3">
                <FiFileText className="w-5 h-5 text-white" />
                <h2 className="font-semibold text-white">Three-Day Notice to Pay Rent or Vacate</h2>
              </div>
              <button
                onClick={() => setIsOpen(false)}
                className="p-2 hover:bg-white/20 rounded-lg transition-colors text-white/80 hover:text-white"
              >
                <FiX className="w-5 h-5" />
              </button>
            </div>

            {/* Document Content */}
            <div className="p-8 overflow-y-auto max-h-[calc(90vh-120px)] bg-white">
              <div className="document-preview max-w-2xl mx-auto">
                <h1>THREE-DAY NOTICE TO PAY RENT OR VACATE</h1>

                <p><strong>Date:</strong> November 28, 2025</p>

                <p>
                  <strong>To:</strong> John Smith<br />
                  1234 Oak Street, Unit 2B<br />
                  Austin, TX 78701
                </p>

                <p><strong>RE:</strong> Notice to Pay Rent or Vacate Premises</p>

                <p>Dear Mr. Smith,</p>

                <p>
                  You are hereby notified that you are in default of your rental agreement for the
                  above-referenced premises. As of the date of this notice, you owe the following amounts:
                </p>

                <table className="w-full my-4 border-collapse">
                  <tbody>
                    <tr>
                      <td className="py-1">Rent Due (November 2025):</td>
                      <td className="py-1 text-right">$1,850.00</td>
                    </tr>
                    <tr>
                      <td className="py-1">Late Fee:</td>
                      <td className="py-1 text-right">$92.50</td>
                    </tr>
                    <tr className="border-t border-gray-300 font-bold">
                      <td className="py-1">TOTAL AMOUNT DUE:</td>
                      <td className="py-1 text-right">$1,942.50</td>
                    </tr>
                  </tbody>
                </table>

                <h2>NOTICE REQUIREMENTS UNDER TEXAS LAW</h2>

                <p>
                  Pursuant to <strong>Texas Property Code § 24.005</strong>, you are hereby given
                  <strong> THREE (3) DAYS</strong> from the date of delivery of this notice to either:
                </p>

                <ol className="list-decimal pl-6 my-4 space-y-2">
                  <li>Pay the total amount due in full; OR</li>
                  <li>Vacate and surrender possession of the premises.</li>
                </ol>

                <h2>PAYMENT INSTRUCTIONS</h2>

                <p>
                  Payment must be made by certified check, cashier&apos;s check, or money order payable to:
                </p>

                <p className="ml-6 my-4">
                  <strong>ABC Property Management LLC</strong><br />
                  5678 Main Street, Suite 100<br />
                  Austin, TX 78702
                </p>

                <h2>CONSEQUENCES OF NON-COMPLIANCE</h2>

                <p>
                  If payment is not received or the premises are not vacated within three (3) days
                  of this notice, legal proceedings may be initiated against you for:
                </p>

                <ul className="list-disc pl-6 my-4 space-y-1">
                  <li>Forcible entry and detainer (eviction)</li>
                  <li>Recovery of all unpaid rent and late fees</li>
                  <li>Court costs and reasonable attorney&apos;s fees</li>
                  <li>Any additional damages permitted by law</li>
                </ul>

                <p>
                  This notice is provided in accordance with the terms of your lease agreement
                  and Texas Property Code Chapter 24.
                </p>

                <p className="mt-8">Sincerely,</p>

                <div className="signature-line mt-12">
                  <p><strong>Jane Doe</strong><br />
                  Property Manager<br />
                  ABC Property Management LLC<br />
                  Phone: (512) 555-0123<br />
                  Email: jane@abcproperties.com</p>
                </div>

                <div className="mt-12 pt-8 border-t border-gray-300">
                  <h2>CERTIFICATE OF SERVICE</h2>
                  <p>
                    I certify that a copy of this notice was delivered to the above-named tenant
                    on November 28, 2025 by the following method:
                  </p>
                  <ul className="list-none my-4 space-y-1">
                    <li>☐ Personal delivery to tenant</li>
                    <li>☐ Personal delivery to person residing at premises over 16 years of age</li>
                    <li>☐ Affixed to inside of main entry door</li>
                  </ul>
                  <div className="signature-line mt-8">
                    Signature of Person Serving Notice
                  </div>
                </div>

                <div className="mt-8 p-4 bg-gray-100 rounded-lg text-sm text-gray-600 italic">
                  <strong>DISCLAIMER:</strong> This document was generated by Tenant Wise AI and is
                  provided as a template only. It does not constitute legal advice. Consult a
                  licensed Texas attorney for legal guidance.
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
