import Link from "next/link";
import { DocumentSparkles } from "@/components/icons/DocumentSparkles";
import { MenuButton, PageWrapper } from "@/components/MenuButton";

export const metadata = {
  title: "Terms of Service | Tenant Wise",
  description: "Terms of Service for Tenant Wise - Terms and conditions governing use of our services.",
};

export default function TermsOfServicePage() {
  return (
    <PageWrapper>
      <div className="min-h-screen bg-muted">
        <MenuButton />

      {/* Content */}
      <div className="max-w-4xl mx-auto px-4 py-12">
        <div className="bg-white rounded-xl shadow-sm border border-border p-8 md:p-12">
          <h1 className="text-3xl font-bold mb-2">TERMS OF SERVICE</h1>
          <p className="text-muted-foreground mb-8">
            Effective Date: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
          </p>

          <div className="prose prose-slate max-w-none">
            <Section title="1. AGREEMENT TO TERMS">
              <p>
                These Terms of Service (&quot;Terms&quot; or &quot;Agreement&quot;) constitute a legally binding
                agreement between you (&quot;User,&quot; &quot;you,&quot; or &quot;your&quot;) and Tenant Wise (&quot;Company,&quot;
                &quot;we,&quot; &quot;our,&quot; or &quot;us&quot;), governing your access to and use of the Tenant Wise
                web application, website, and all related services (collectively, the &quot;Services&quot;).
              </p>
              <p>
                BY ACCESSING OR USING THE SERVICES, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD,
                AND AGREE TO BE BOUND BY THESE TERMS. IF YOU DO NOT AGREE TO THESE TERMS, YOU MUST
                NOT ACCESS OR USE THE SERVICES.
              </p>
              <p>
                You represent and warrant that you are at least eighteen (18) years of age and have
                the legal capacity to enter into this Agreement. If you are entering into this
                Agreement on behalf of a business entity, you represent and warrant that you have
                the authority to bind such entity to these Terms.
              </p>
            </Section>

            <Section title="2. DESCRIPTION OF SERVICES">
              <p>
                Tenant Wise provides a software-as-a-service platform designed for residential
                property landlords operating in the State of Texas. The Services include, but are
                not limited to:
              </p>
              <ul className="list-disc pl-6 space-y-1">
                <li>AI-powered generation of landlord-tenant legal documents and notices</li>
                <li>Property and tenant information management</li>
                <li>Document storage and retrieval</li>
                <li>Templates for Texas-compliant landlord communications</li>
              </ul>
              <p className="mt-4">
                The Company reserves the right to modify, suspend, or discontinue any aspect of
                the Services at any time, with or without notice. The Company shall not be liable
                to you or any third party for any modification, suspension, or discontinuation of
                the Services.
              </p>
            </Section>

            <Section title="3. IMPORTANT DISCLAIMERS REGARDING LEGAL DOCUMENTS">
              <p className="font-semibold text-foreground">
                PLEASE READ THIS SECTION CAREFULLY AS IT AFFECTS YOUR LEGAL RIGHTS.
              </p>
              <p>
                THE SERVICES GENERATE DOCUMENT TEMPLATES USING ARTIFICIAL INTELLIGENCE TECHNOLOGY.
                THESE DOCUMENTS ARE PROVIDED FOR INFORMATIONAL PURPOSES ONLY AND DO NOT CONSTITUTE
                LEGAL ADVICE, LEGAL OPINIONS, OR LEGAL REPRESENTATION.
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>
                  <strong>Not a Law Firm:</strong> Tenant Wise is not a law firm and does not
                  provide legal services. No attorney-client relationship is created by your use
                  of the Services.
                </li>
                <li>
                  <strong>No Guarantee of Compliance:</strong> While documents are designed to
                  comply with Texas Property Code and other applicable Texas laws, we do not
                  guarantee that any document will be legally enforceable, compliant with current
                  law, or appropriate for your specific circumstances.
                </li>
                <li>
                  <strong>Consult an Attorney:</strong> You are strongly advised to consult with
                  a licensed Texas attorney before using any document generated by the Services
                  in any legal proceeding or binding transaction.
                </li>
                <li>
                  <strong>User Responsibility:</strong> You are solely responsible for reviewing,
                  verifying, and ensuring the accuracy and appropriateness of any document before use.
                </li>
                <li>
                  <strong>AI Limitations:</strong> AI-generated content may contain errors,
                  omissions, or outdated information. Laws change frequently, and the Services
                  may not reflect the most current legal requirements.
                </li>
              </ul>
            </Section>

            <Section title="4. USER ACCOUNTS">
              <h4 className="font-semibold mt-4 mb-2">4.1 Account Registration</h4>
              <p>
                To access certain features of the Services, you must register for an account.
                You agree to provide accurate, current, and complete information during registration
                and to update such information to keep it accurate, current, and complete.
              </p>

              <h4 className="font-semibold mt-4 mb-2">4.2 Account Security</h4>
              <p>
                You are responsible for maintaining the confidentiality of your account credentials
                and for all activities that occur under your account. You agree to notify the
                Company immediately of any unauthorized use of your account or any other breach
                of security. The Company shall not be liable for any loss or damage arising from
                your failure to protect your account credentials.
              </p>

              <h4 className="font-semibold mt-4 mb-2">4.3 Account Termination</h4>
              <p>
                The Company reserves the right to suspend or terminate your account at any time,
                with or without cause, and with or without notice. Upon termination, your right
                to use the Services will immediately cease, and you must cease all use of the Services.
              </p>
            </Section>

            <Section title="5. SUBSCRIPTION PLANS AND PAYMENT TERMS">
              <h4 className="font-semibold mt-4 mb-2">5.1 Subscription Tiers</h4>
              <p>The Services are offered under the following subscription tiers:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li><strong>Free Tier:</strong> Limited to three (3) documents per calendar month</li>
                <li><strong>Basic Tier ($19/month):</strong> Unlimited documents and all document templates</li>
                <li><strong>Pro Tier ($39/month):</strong> All Basic features plus multi-property support, tenant profiles, and document history</li>
              </ul>

              <h4 className="font-semibold mt-4 mb-2">5.2 Billing and Payment</h4>
              <p>
                Paid subscriptions are billed in advance on a monthly basis. Payment is processed
                through Stripe, Inc., our third-party payment processor. By subscribing to a paid
                tier, you authorize the Company to charge your designated payment method on a
                recurring basis.
              </p>

              <h4 className="font-semibold mt-4 mb-2">5.3 Price Changes</h4>
              <p>
                The Company reserves the right to modify subscription prices at any time. Price
                changes will be communicated to you at least thirty (30) days before taking effect.
                Your continued use of the Services after a price change constitutes acceptance of
                the new pricing.
              </p>

              <h4 className="font-semibold mt-4 mb-2">5.4 Refund Policy</h4>
              <p>
                Subscription fees are non-refundable except as required by applicable law. If you
                cancel your subscription, you will retain access to paid features until the end of
                your current billing period.
              </p>

              <h4 className="font-semibold mt-4 mb-2">5.5 Taxes</h4>
              <p>
                All fees are exclusive of applicable taxes. You are responsible for paying all
                taxes associated with your use of the Services, including but not limited to
                Texas state sales tax where applicable.
              </p>
            </Section>

            <Section title="6. ACCEPTABLE USE POLICY">
              <p>You agree not to use the Services to:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li>Violate any applicable federal, state, or local law, including but not limited to Texas Property Code, Texas Business and Commerce Code, or fair housing laws</li>
                <li>Generate documents for fraudulent, deceptive, or illegal purposes</li>
                <li>Harass, threaten, or intimidate tenants or any other individuals</li>
                <li>Infringe upon the intellectual property rights of others</li>
                <li>Transmit viruses, malware, or other malicious code</li>
                <li>Attempt to gain unauthorized access to the Services or related systems</li>
                <li>Interfere with or disrupt the integrity or performance of the Services</li>
                <li>Collect or harvest personal information of other users</li>
                <li>Use the Services for any purpose that violates the Texas Deceptive Trade Practices-Consumer Protection Act (DTPA)</li>
                <li>Sublicense, resell, or redistribute the Services without prior written consent</li>
              </ul>
              <p className="mt-4">
                Violation of this Acceptable Use Policy may result in immediate termination of
                your account and may subject you to civil and criminal liability.
              </p>
            </Section>

            <Section title="7. INTELLECTUAL PROPERTY RIGHTS">
              <h4 className="font-semibold mt-4 mb-2">7.1 Company Intellectual Property</h4>
              <p>
                The Services, including all software, content, features, functionality, design
                elements, trademarks, and trade dress, are owned by the Company and are protected
                by United States and international copyright, trademark, patent, trade secret,
                and other intellectual property laws.
              </p>

              <h4 className="font-semibold mt-4 mb-2">7.2 Limited License</h4>
              <p>
                Subject to these Terms, the Company grants you a limited, non-exclusive,
                non-transferable, revocable license to access and use the Services for your
                personal or internal business purposes. This license does not include the right to:
              </p>
              <ul className="list-disc pl-6 space-y-1">
                <li>Modify, copy, or create derivative works of the Services</li>
                <li>Reverse engineer, decompile, or disassemble any aspect of the Services</li>
                <li>Remove or alter any proprietary notices or labels</li>
                <li>Use the Services for competitive analysis or to develop a competing product</li>
              </ul>

              <h4 className="font-semibold mt-4 mb-2">7.3 User Content</h4>
              <p>
                You retain ownership of all data, information, and content you submit to the
                Services (&quot;User Content&quot;). By submitting User Content, you grant the Company
                a limited license to use, process, and store such content solely for the purpose
                of providing the Services to you.
              </p>

              <h4 className="font-semibold mt-4 mb-2">7.4 Generated Documents</h4>
              <p>
                Documents generated through the Services are provided to you for your use. You
                may use, modify, and distribute generated documents for your legitimate landlord
                business purposes. However, you may not resell or commercially distribute the
                document generation functionality itself.
              </p>
            </Section>

            <Section title="8. PRIVACY">
              <p>
                Your use of the Services is also governed by our Privacy Policy, which is
                incorporated into these Terms by reference. Please review our{" "}
                <Link href="/privacy" className="text-blue-600 hover:underline">
                  Privacy Policy
                </Link>{" "}
                to understand our practices regarding the collection, use, and disclosure of
                your personal information.
              </p>
            </Section>

            <Section title="9. DISCLAIMER OF WARRANTIES">
              <p className="font-semibold text-foreground">
                TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW:
              </p>
              <p>
                THE SERVICES ARE PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY
                KIND, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE. THE COMPANY EXPRESSLY
                DISCLAIMS ALL WARRANTIES, INCLUDING BUT NOT LIMITED TO:
              </p>
              <ul className="list-disc pl-6 space-y-1">
                <li>IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT</li>
                <li>WARRANTIES THAT THE SERVICES WILL BE UNINTERRUPTED, ERROR-FREE, OR SECURE</li>
                <li>WARRANTIES REGARDING THE ACCURACY, RELIABILITY, OR COMPLETENESS OF ANY CONTENT OR INFORMATION</li>
                <li>WARRANTIES THAT GENERATED DOCUMENTS WILL BE LEGALLY COMPLIANT OR ENFORCEABLE</li>
                <li>WARRANTIES THAT THE SERVICES WILL MEET YOUR REQUIREMENTS OR EXPECTATIONS</li>
              </ul>
              <p className="mt-4">
                Some jurisdictions do not allow the exclusion of implied warranties, so the above
                exclusions may not apply to you. In such cases, the Company&apos;s liability shall be
                limited to the maximum extent permitted by law.
              </p>
            </Section>

            <Section title="10. LIMITATION OF LIABILITY">
              <p className="font-semibold text-foreground">
                TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW:
              </p>
              <p>
                IN NO EVENT SHALL THE COMPANY, ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS,
                AFFILIATES, OR LICENSORS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
                CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO:
              </p>
              <ul className="list-disc pl-6 space-y-1">
                <li>Loss of profits, revenue, or business opportunities</li>
                <li>Loss of data or data breach</li>
                <li>Legal fees, fines, or penalties arising from use of generated documents</li>
                <li>Damages arising from tenant disputes or legal proceedings</li>
                <li>Damages arising from reliance on AI-generated content</li>
                <li>Any damages arising from events beyond the Company&apos;s reasonable control</li>
              </ul>
              <p className="mt-4">
                THE COMPANY&apos;S TOTAL CUMULATIVE LIABILITY ARISING OUT OF OR RELATED TO THESE TERMS
                OR THE SERVICES SHALL NOT EXCEED THE GREATER OF: (A) THE AMOUNTS PAID BY YOU TO
                THE COMPANY IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM; OR (B) ONE HUNDRED
                DOLLARS ($100.00).
              </p>
              <p className="mt-4">
                THE LIMITATIONS IN THIS SECTION APPLY REGARDLESS OF THE THEORY OF LIABILITY,
                WHETHER BASED ON WARRANTY, CONTRACT, STATUTE, TORT (INCLUDING NEGLIGENCE), OR
                OTHERWISE, AND REGARDLESS OF WHETHER THE COMPANY HAS BEEN ADVISED OF THE
                POSSIBILITY OF SUCH DAMAGES.
              </p>
            </Section>

            <Section title="11. INDEMNIFICATION">
              <p>
                You agree to defend, indemnify, and hold harmless the Company and its officers,
                directors, employees, agents, affiliates, and licensors from and against any and
                all claims, damages, obligations, losses, liabilities, costs, and expenses
                (including reasonable attorneys&apos; fees) arising from or related to:
              </p>
              <ul className="list-disc pl-6 space-y-1">
                <li>Your use of the Services</li>
                <li>Your violation of these Terms</li>
                <li>Your violation of any applicable law or regulation</li>
                <li>Your use of any document generated through the Services</li>
                <li>Any dispute between you and your tenants or other third parties</li>
                <li>Your User Content or any content you submit to the Services</li>
                <li>Your infringement of any third-party rights</li>
              </ul>
              <p className="mt-4">
                The Company reserves the right, at its own expense, to assume the exclusive
                defense and control of any matter subject to indemnification by you, in which
                event you agree to cooperate with the Company in asserting any available defenses.
              </p>
            </Section>

            <Section title="12. DISPUTE RESOLUTION">
              <h4 className="font-semibold mt-4 mb-2">12.1 Governing Law</h4>
              <p>
                These Terms and any dispute arising out of or related to these Terms or the
                Services shall be governed by and construed in accordance with the laws of the
                State of Texas, without regard to its conflict of law provisions.
              </p>

              <h4 className="font-semibold mt-4 mb-2">12.2 Jurisdiction and Venue</h4>
              <p>
                Any legal action or proceeding arising out of or related to these Terms or the
                Services shall be brought exclusively in the state or federal courts located in
                Travis County, Texas. You hereby consent to the personal jurisdiction and venue
                of such courts and waive any objection based on inconvenient forum.
              </p>

              <h4 className="font-semibold mt-4 mb-2">12.3 Informal Resolution</h4>
              <p>
                Before initiating any legal proceeding, you agree to first contact the Company
                and attempt to resolve the dispute informally. You may contact us at the address
                provided in Section 17. The Company will attempt to resolve the dispute within
                thirty (30) days.
              </p>

              <h4 className="font-semibold mt-4 mb-2">12.4 Waiver of Class Actions</h4>
              <p>
                TO THE MAXIMUM EXTENT PERMITTED BY LAW, YOU AGREE THAT ANY DISPUTE RESOLUTION
                PROCEEDINGS WILL BE CONDUCTED ONLY ON AN INDIVIDUAL BASIS AND NOT IN A CLASS,
                CONSOLIDATED, OR REPRESENTATIVE ACTION. YOU WAIVE ANY RIGHT TO PARTICIPATE IN
                A CLASS ACTION LAWSUIT OR CLASS-WIDE ARBITRATION.
              </p>

              <h4 className="font-semibold mt-4 mb-2">12.5 Limitation Period</h4>
              <p>
                Any claim or cause of action arising out of or related to these Terms or the
                Services must be filed within one (1) year after such claim or cause of action
                arose, or it shall be forever barred.
              </p>
            </Section>

            <Section title="13. TERMINATION">
              <h4 className="font-semibold mt-4 mb-2">13.1 Termination by You</h4>
              <p>
                You may terminate your account at any time by contacting customer support or
                using the account settings in the Services. Upon termination, you will lose
                access to the Services and any data stored in your account.
              </p>

              <h4 className="font-semibold mt-4 mb-2">13.2 Termination by Company</h4>
              <p>
                The Company may terminate or suspend your account immediately, without prior
                notice or liability, for any reason, including but not limited to breach of
                these Terms. Upon termination, your right to use the Services will cease immediately.
              </p>

              <h4 className="font-semibold mt-4 mb-2">13.3 Effect of Termination</h4>
              <p>
                Upon termination, the following provisions shall survive: Sections 3 (Disclaimers),
                7 (Intellectual Property), 9 (Disclaimer of Warranties), 10 (Limitation of Liability),
                11 (Indemnification), 12 (Dispute Resolution), and any other provisions that by
                their nature should survive termination.
              </p>
            </Section>

            <Section title="14. MODIFICATIONS TO TERMS">
              <p>
                The Company reserves the right to modify these Terms at any time. If we make
                material changes, we will provide notice by:
              </p>
              <ul className="list-disc pl-6 space-y-1">
                <li>Posting the revised Terms on this page with an updated effective date</li>
                <li>Sending notice to the email address associated with your account</li>
                <li>Displaying a prominent notice within the Services</li>
              </ul>
              <p className="mt-4">
                Your continued use of the Services following the posting of revised Terms
                constitutes your acceptance of such changes. If you do not agree to the revised
                Terms, you must discontinue use of the Services.
              </p>
            </Section>

            <Section title="15. GENERAL PROVISIONS">
              <h4 className="font-semibold mt-4 mb-2">15.1 Entire Agreement</h4>
              <p>
                These Terms, together with the Privacy Policy and any other agreements expressly
                incorporated by reference, constitute the entire agreement between you and the
                Company regarding the Services and supersede all prior agreements and understandings.
              </p>

              <h4 className="font-semibold mt-4 mb-2">15.2 Severability</h4>
              <p>
                If any provision of these Terms is held to be invalid, illegal, or unenforceable,
                such provision shall be modified to the minimum extent necessary to make it valid
                and enforceable, or if modification is not possible, shall be severed from these
                Terms. The remaining provisions shall continue in full force and effect.
              </p>

              <h4 className="font-semibold mt-4 mb-2">15.3 Waiver</h4>
              <p>
                The failure of the Company to enforce any right or provision of these Terms shall
                not constitute a waiver of such right or provision. Any waiver must be in writing
                and signed by an authorized representative of the Company.
              </p>

              <h4 className="font-semibold mt-4 mb-2">15.4 Assignment</h4>
              <p>
                You may not assign or transfer these Terms or your rights hereunder without the
                prior written consent of the Company. The Company may assign these Terms without
                restriction. Subject to the foregoing, these Terms shall bind and inure to the
                benefit of the parties and their respective successors and assigns.
              </p>

              <h4 className="font-semibold mt-4 mb-2">15.5 Force Majeure</h4>
              <p>
                The Company shall not be liable for any failure or delay in performance resulting
                from causes beyond its reasonable control, including but not limited to acts of
                God, natural disasters, war, terrorism, riots, embargoes, acts of civil or military
                authorities, fire, floods, accidents, strikes, or shortages of transportation,
                facilities, fuel, energy, labor, or materials.
              </p>

              <h4 className="font-semibold mt-4 mb-2">15.6 Notices</h4>
              <p>
                All notices required or permitted under these Terms shall be in writing. Notices
                to you may be sent to the email address associated with your account. Notices to
                the Company shall be sent to the address provided in Section 17.
              </p>

              <h4 className="font-semibold mt-4 mb-2">15.7 Electronic Communications</h4>
              <p>
                By using the Services, you consent to receive electronic communications from the
                Company. You agree that all agreements, notices, disclosures, and other communications
                provided electronically satisfy any legal requirement that such communications be
                in writing.
              </p>
            </Section>

            <Section title="16. TEXAS-SPECIFIC PROVISIONS">
              <p>
                The following provisions apply specifically to users in the State of Texas:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>
                  <strong>Texas Deceptive Trade Practices Act:</strong> Nothing in these Terms
                  shall be construed to waive any rights you may have under the Texas Deceptive
                  Trade Practices-Consumer Protection Act (Texas Business and Commerce Code,
                  Chapter 17), to the extent such rights cannot be waived by law.
                </li>
                <li>
                  <strong>Texas Property Code Compliance:</strong> While the Services are designed
                  to generate documents compliant with Texas Property Code, you are solely
                  responsible for ensuring compliance with all applicable sections, including
                  but not limited to Chapters 24, 91, 92, and 93.
                </li>
                <li>
                  <strong>Fair Housing:</strong> You agree to comply with all applicable fair
                  housing laws, including the Texas Fair Housing Act (Texas Property Code,
                  Chapter 301) and the federal Fair Housing Act. The Services shall not be used
                  to discriminate against any person based on race, color, religion, sex, familial
                  status, national origin, disability, or any other protected characteristic.
                </li>
              </ul>
            </Section>

            <Section title="17. CONTACT INFORMATION">
              <p>
                For questions, concerns, or notices regarding these Terms, please contact:
              </p>
              <div className="mt-4 p-4 bg-slate-50 rounded-lg">
                <p className="font-semibold">Tenant Wise</p>
                <p>Attn: Legal Department</p>
                <p className="mt-2">
                  <strong>Email:</strong>{" "}
                  <a href="mailto:legal@tenantwise.ai" className="text-blue-600 hover:underline">
                    legal@tenantwise.ai
                  </a>
                </p>
                <p>
                  <strong>Website:</strong>{" "}
                  <Link href="/" className="text-blue-600 hover:underline">
                    www.tenantwise.ai
                  </Link>
                </p>
              </div>
            </Section>

            <div className="mt-12 pt-8 border-t border-border">
              <p className="text-sm text-muted-foreground italic">
                BY USING THE SERVICES, YOU ACKNOWLEDGE THAT YOU HAVE READ THESE TERMS OF SERVICE,
                UNDERSTAND THEM, AND AGREE TO BE BOUND BY THEM. IF YOU DO NOT AGREE TO THESE TERMS,
                DO NOT USE THE SERVICES.
              </p>
              <p className="text-sm text-muted-foreground italic mt-4">
                These Terms of Service are provided for informational purposes and constitute a
                binding legal agreement. This document does not constitute legal advice. If you
                have questions about your legal rights or obligations, please consult with a
                licensed attorney in your jurisdiction.
              </p>
            </div>
          </div>
        </div>
      </div>

      </div>
    </PageWrapper>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-8">
      <h2 className="text-xl font-semibold mb-4 text-foreground">{title}</h2>
      <div className="text-muted-foreground space-y-3">{children}</div>
    </section>
  );
}
